// Copyright ©2025 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package vgtyp provides a vg.Canvas implementation for Typst, targeted at
// the CeTZ package: https://typst.app/universe/package/cetz
//
// vgtyp generates CeTZ instructions that will be interpreted and rendered by Typst.
package vgtyp // import "gonum.org/v1/plot/vg/vgtyp"

import (
	"bufio"
	"bytes"
	"encoding/base64"
	"fmt"
	"image"
	"image/color"
	"image/png"
	"io"
	"math"
	"strings"
	"time"

	"gonum.org/v1/plot/font"
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
)

const degPerRadian = 180 / math.Pi

const (
	defaultHeader = `// generated by gonum/plot

#import "@preview/based:0.1.0": base64
#import "@preview/cetz:0.4.2"

#set page(width: %gpt, height: %gpt, margin: (x: 0pt, y: 0pt))

#cetz.canvas(length: 1pt, {
	import cetz.draw: *
`
	defaultFooter = "\n})\n"
)

func init() {
	draw.RegisterFormat("typ", func(w, h vg.Length) vg.CanvasWriterTo {
		return New(w, h)
	})
}

// Canvas implements the vg.Canvas interface, translating drawing
// primitives from gonum/plot to Typst/CeTZ.
type Canvas struct {
	buf   *bytes.Buffer
	w, h  vg.Length
	stack []context

	id int64 // id is a unique identifier for this canvas
}

type context struct {
	color      color.Color
	dashArray  []vg.Length
	dashOffset vg.Length
	linew      vg.Length
}

// New returns a new Typst canvas.
func New(w, h vg.Length) *Canvas {
	c := &Canvas{
		buf: new(bytes.Buffer),
		w:   w,
		h:   h,
		id:  time.Now().UnixNano(),
	}
	c.wtyp("")
	c.stack = make([]context, 1)
	vg.Initialize(c)
	return c
}

func (c *Canvas) context() *context {
	return &c.stack[len(c.stack)-1]
}

// Size returns the width and height of the canvas.
func (c *Canvas) Size() (w, h vg.Length) {
	return c.w, c.h
}

// SetLineWidth implements the vg.Canvas.SetLineWidth method.
func (c *Canvas) SetLineWidth(w vg.Length) {
	c.context().linew = w
}

// SetLineDash implements the vg.Canvas.SetLineDash method.
func (c *Canvas) SetLineDash(pattern []vg.Length, offset vg.Length) {
	c.context().dashArray = pattern
	c.context().dashOffset = offset
}

// SetColor implements the vg.Canvas.SetColor method.
func (c *Canvas) SetColor(clr color.Color) {
	c.context().color = clr
}

// Rotate implements the vg.Canvas.Rotate method.
func (c *Canvas) Rotate(rad float64) {
	c.wtyp("rotate(z: %grad)", rad)
}

// Translate implements the vg.Canvas.Translate method.
func (c *Canvas) Translate(pt vg.Point) {
	c.wtyp("translate(x: %gpt, y: %gpt)", pt.X, pt.Y)
}

// Scale implements the vg.Canvas.Scale method.
func (c *Canvas) Scale(x, y float64) {
	c.wtyp("scale(x: %g, y: %g)", x, y)
}

// Push implements the vg.Canvas.Push method.
func (c *Canvas) Push() {
	c.wtyp("group({")
	c.stack = append(c.stack, *c.context())
}

// Pop implements the vg.Canvas.Pop method.
func (c *Canvas) Pop() {
	c.stack = c.stack[:len(c.stack)-1]
	c.wtyp("})")
	c.wtyp("")
}

// Stroke implements the vg.Canvas.Stroke method.
func (c *Canvas) Stroke(p vg.Path) {
	if c.context().linew <= 0 {
		return
	}
	c.Push()
	c.wstyle()
	c.wtyp(`merge-path({ // stroke`)
	c.wpath(p)
	c.wtyp("}) // merge-path")
	c.Pop()
}

// Fill implements the vg.Canvas.Fill method.
func (c *Canvas) Fill(p vg.Path) {
	c.Push()
	c.wstyle()
	c.wtyp("merge-path(fill: %s, { // fill", c.wcolor())
	c.wpath(p)
	c.wtyp("}) // merge-path")
	c.Pop()
}

// FillString implements the vg.Canvas.FillString method.
func (c *Canvas) FillString(f font.Face, pt vg.Point, text string) {
	pt.X += 0.5 * f.Width(text)
	//pt.Y += 0.25 * f.Extents().Height
	c.wtyp(
		`content((%gpt, %gpt), box([
			#set text(size: %gpt, fill: %s)
			%s
		]))`,
		pt.X, pt.Y,
		//f.Extents().Height,
		//f.Width(text),
		f.Font.Size/2,
		c.wcolor(),
		text,
	)
}

// DrawImage implements the vg.Canvas.DrawImage method.
func (c *Canvas) DrawImage(rect vg.Rectangle, img image.Image) {
	buf := new(bytes.Buffer)
	err := png.Encode(buf, img)
	if err != nil {
		panic(fmt.Errorf("vgtyp: error encoding image to PNG: %v", err))
	}

	var (
		xmin   = rect.Min.X
		ymin   = rect.Min.Y
		width  = rect.Size().X
		height = rect.Size().Y
	)
	c.wtyp("content((%gpt, %gpt), box(width: %gpt, height: %gpt, image.decode(base64.decode(\"%s\"))))",
		xmin+width/2, ymin+height/2,
		width, height,
		base64.StdEncoding.EncodeToString(buf.Bytes()),
	)
}

func (c *Canvas) indent(s string) string {
	return strings.Repeat(s, len(c.stack))
}

func (c *Canvas) wtyp(s string, args ...any) {
	fmt.Fprintf(c.buf, c.indent("  ")+s+"\n", args...)
}

func (c *Canvas) wstyle() {
	c.wtyp(
		"set-style(stroke: (paint: %s, thickness: %s, dash: %s))",
		c.wcolor(),
		c.thickness(),
		c.wdash(),
	)
}

func (c *Canvas) wdash() string {
	if len(c.context().dashArray) == 0 {
		//return "none"
		return `"solid"`
	}
	o := new(strings.Builder)
	o.WriteString(`(`)
	for i, d := range c.context().dashArray {
		if i > 0 {
			o.WriteString(", ")
		}
		fmt.Fprintf(o, "%gpt", d)
	}
	o.WriteString(")")
	return o.String()
}

func (c *Canvas) thickness() string {
	return fmt.Sprintf("%gpt", c.context().linew)
}

func (c *Canvas) wcolor() string {
	col := c.context().color
	if col == nil {
		col = color.Black
	}
	r, g, b, a := col.RGBA()
	return fmt.Sprintf("rgb(%g%%, %g%%, %g%%, %g%%)",
		float64(r)/math.MaxUint16*100,
		float64(g)/math.MaxUint16*100,
		float64(b)/math.MaxUint16*100,
		float64(a)/math.MaxUint16*100,
	)
}

func (c *Canvas) wpath(p vg.Path) {
	var ctx vg.Point
	for _, comp := range p {
		switch comp.Type {
		case vg.MoveComp:
			c.wtyp(`move-to((%gpt, %gpt))`, comp.Pos.X, comp.Pos.Y)
			ctx = comp.Pos
		case vg.LineComp:
			c.wtyp(`line((%gpt, %gpt), (%gpt, %gpt))`, ctx.X, ctx.Y, comp.Pos.X, comp.Pos.Y)
			ctx = comp.Pos
		case vg.ArcComp:
			ctx = c.arc(comp, ctx)

		case vg.CurveComp:
			c.wtyp("bezier((%gpt, %gpt),", ctx.X, ctx.Y)
			switch len(comp.Control) {
			case 1:
				c.wtyp("(%gpt, %gpt),", comp.Control[0].X, comp.Control[0].Y)
			case 2:
				c.wtyp("(%gpt, %gpt), (%gpt, %gpt),",
					comp.Control[0].X, comp.Control[0].Y,
					comp.Control[1].X, comp.Control[1].Y,
				)
			default:
				panic("vgtyp: invalid number of control points")
			}
			c.wtyp("(%gpt, %gpt)))", comp.Pos.X, comp.Pos.Y)
			ctx = comp.Pos
		case vg.CloseComp:
			//c.wtyp("close: true,")
		default:
			panic(fmt.Errorf("vgtyp: unknown path component type: %v", comp.Type))
		}
	}
}

// WriteTo implements the io.WriterTo interface, writing a LaTeX/pgf plot.
func (c *Canvas) WriteTo(w io.Writer) (int64, error) {
	var (
		b   = bufio.NewWriter(w)
		n   int64
		nn  int
		err error
	)

	nn, err = b.Write([]byte(fmt.Sprintf(defaultHeader, c.w.Points(), c.h.Points())))
	n += int64(nn)
	if err != nil {
		return n, err
	}

	m, err := c.buf.WriteTo(b)
	n += m
	if err != nil {
		return n, err
	}

	nn, err = b.Write([]byte(defaultFooter))
	n += int64(nn)
	if err != nil {
		return n, err
	}

	return n, b.Flush()
}

func (c *Canvas) arc(comp vg.PathComp, ctx vg.Point) vg.Point {
	// x0 := comp.Pos.X + comp.Radius*vg.Length(math.Cos(comp.Start))
	// y0 := comp.Pos.Y + comp.Radius*vg.Length(math.Sin(comp.Start))
	// c.wtyp("move-to((%gpt, %gpt))", x0, y0)
	// // //c.wtyp("line((%gpt, %gpt), (%gpt, %gpt))", ctx.X, ctx.Y, x0, y0)
	var (
		angle = comp.Angle //* degPerRadian
		beg   = comp.Start //* degPerRadian
		end   = beg + angle
		x     = comp.Pos.X
		y     = comp.Pos.Y
	)
	c.wtyp("arc((%gpt, %gpt), start: %grad, stop: %grad)",
		x, y, beg, end,
	)
	x1 := comp.Pos.X + comp.Radius*vg.Length(math.Cos(comp.Start+comp.Angle))
	y1 := comp.Pos.Y + comp.Radius*vg.Length(math.Sin(comp.Start+comp.Angle))
	c.wtyp("move-to((%gpt, %gpt))", x1, y1)
	return vg.Point{X: x1, Y: y1}
}
