// generated by gonum/plot

#import "@preview/based:0.1.0": base64
#import "@preview/cetz:0.4.2"

#set page(width: 141.73228346456693pt, height: 141.73228346456693pt, margin: (x: 0pt, y: 0pt))

#cetz.canvas(length: 1pt, {
	import cetz.draw: *

  group({
    set-style(stroke: (paint: rgb(100%, 100%, 100%, 100%), thickness: 1pt, dash: "solid"))
    merge-path(fill: rgb(100%, 100%, 100%, 100%), { // fill
    move-to((0pt, 0pt))
    line((0pt, 0pt), (141.73228346456693pt, 0pt))
    line((141.73228346456693pt, 0pt), (141.73228346456693pt, 141.73228346456693pt))
    line((141.73228346456693pt, 141.73228346456693pt), (0pt, 141.73228346456693pt))
    }) // merge-path
  })
  
  content((70.86614173228347pt, 129.21665846456693pt), box([
			#set text(size: 10pt, fill: rgb(0%, 0%, 0%, 100%))
			A scatter plot: $sqrt((e^(3i pi))/(2 cos 3 pi))$
		]))
  content((91.30852454478347pt, 5.90234375pt), box([
			#set text(size: 6pt, fill: rgb(0%, 0%, 0%, 100%))
			$x = eta$
		]))
  content((47.134765625pt, 16.541015625pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			0.0
		]))
  content((91.30852454478347pt, 16.541015625pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			0.5
		]))
  content((135.48228346456693pt, 16.541015625pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			1.0
		]))
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((47.134765625pt, 24.36328125pt))
    line((47.134765625pt, 24.36328125pt), (47.134765625pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((91.30852454478347pt, 24.36328125pt))
    line((91.30852454478347pt, 24.36328125pt), (91.30852454478347pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((135.48228346456693pt, 24.36328125pt))
    line((135.48228346456693pt, 24.36328125pt), (135.48228346456693pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((55.96951740895669pt, 28.36328125pt))
    line((55.96951740895669pt, 28.36328125pt), (55.96951740895669pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((64.80426919291338pt, 28.36328125pt))
    line((64.80426919291338pt, 28.36328125pt), (64.80426919291338pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((73.63902097687009pt, 28.36328125pt))
    line((73.63902097687009pt, 28.36328125pt), (73.63902097687009pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((82.47377276082678pt, 28.36328125pt))
    line((82.47377276082678pt, 28.36328125pt), (82.47377276082678pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((100.14327632874017pt, 28.36328125pt))
    line((100.14327632874017pt, 28.36328125pt), (100.14327632874017pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((108.97802811269686pt, 28.36328125pt))
    line((108.97802811269686pt, 28.36328125pt), (108.97802811269686pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((117.81277989665355pt, 28.36328125pt))
    line((117.81277989665355pt, 28.36328125pt), (117.81277989665355pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((126.64753168061024pt, 28.36328125pt))
    line((126.64753168061024pt, 28.36328125pt), (126.64753168061024pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((47.134765625pt, 32.36328125pt))
    line((47.134765625pt, 32.36328125pt), (135.48228346456693pt, 32.36328125pt))
    }) // merge-path
  })
  
  group({
    rotate(z: 1.5707963267948966rad)
    content((79.29485266978347pt, -9.386718749999993pt), box([
			#set text(size: 6pt, fill: rgb(0%, 0%, 0%, 100%))
			$y$ is some $Phi$
		]))
  })
  
  content((22.134765625pt, 37.828125pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			0.0
		]))
  content((22.134765625pt, 77.00969641978347pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			0.5
		]))
  content((22.134765625pt, 116.19126783956693pt), box([
			#set text(size: 5pt, fill: rgb(0%, 0%, 0%, 100%))
			1.0
		]))
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((30.884765625pt, 40.11328125pt))
    line((30.884765625pt, 40.11328125pt), (38.884765625pt, 40.11328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((30.884765625pt, 79.29485266978347pt))
    line((30.884765625pt, 79.29485266978347pt), (38.884765625pt, 79.29485266978347pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((30.884765625pt, 118.47642408956693pt))
    line((30.884765625pt, 118.47642408956693pt), (38.884765625pt, 118.47642408956693pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 47.949595533956696pt))
    line((34.884765625pt, 47.949595533956696pt), (38.884765625pt, 47.949595533956696pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 55.785909817913385pt))
    line((34.884765625pt, 55.785909817913385pt), (38.884765625pt, 55.785909817913385pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 63.62222410187009pt))
    line((34.884765625pt, 63.62222410187009pt), (38.884765625pt, 63.62222410187009pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 71.45853838582677pt))
    line((34.884765625pt, 71.45853838582677pt), (38.884765625pt, 71.45853838582677pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 87.13116695374018pt))
    line((34.884765625pt, 87.13116695374018pt), (38.884765625pt, 87.13116695374018pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 94.96748123769686pt))
    line((34.884765625pt, 94.96748123769686pt), (38.884765625pt, 94.96748123769686pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 102.80379552165354pt))
    line((34.884765625pt, 102.80379552165354pt), (38.884765625pt, 102.80379552165354pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((34.884765625pt, 110.64010980561024pt))
    line((34.884765625pt, 110.64010980561024pt), (38.884765625pt, 110.64010980561024pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 0%, 100%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((38.884765625pt, 40.11328125pt))
    line((38.884765625pt, 40.11328125pt), (38.884765625pt, 118.47642408956693pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(100%, 0%, 0%, 78.43137254901961%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((137.98228346456693pt, 118.47642408956693pt))
    arc((135.48228346456693pt, 118.47642408956693pt), start: 0rad, stop: 6.283185307179586rad)
    move-to((137.98228346456693pt, 118.47642408956693pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(100%, 0%, 0%, 78.43137254901961%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((49.634765625pt, 118.47642408956693pt))
    arc((47.134765625pt, 118.47642408956693pt), start: 0rad, stop: 6.283185307179586rad)
    move-to((49.634765625pt, 118.47642408956693pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(100%, 0%, 0%, 78.43137254901961%), thickness: 0.5pt, dash: "solid"))
    merge-path({ // stroke
    move-to((49.634765625pt, 40.11328125pt))
    arc((47.134765625pt, 40.11328125pt), start: 0rad, stop: 6.283185307179586rad)
    move-to((49.634765625pt, 40.11328125pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 100%, 78.43137254901961%), thickness: 0.5pt, dash: "solid"))
    merge-path(fill: rgb(0%, 0%, 100%, 78.43137254901961%), { // fill
    move-to((135.48228346456693pt, 42.61328124997408pt))
    line((135.48228346456693pt, 42.61328124997408pt), (133.3172199551657pt, 38.86328124994816pt))
    line((133.3172199551657pt, 38.86328124994816pt), (137.64734697396815pt, 38.86328124994816pt))
    }) // merge-path
  })
  
  group({
    set-style(stroke: (paint: rgb(0%, 0%, 100%, 78.43137254901961%), thickness: 0.5pt, dash: "solid"))
    merge-path(fill: rgb(0%, 0%, 100%, 78.43137254901961%), { // fill
    move-to((135.48228346456693pt, 81.79485266975755pt))
    line((135.48228346456693pt, 81.79485266975755pt), (133.3172199551657pt, 78.04485266973163pt))
    line((133.3172199551657pt, 78.04485266973163pt), (137.64734697396815pt, 78.04485266973163pt))
    }) // merge-path
  })
  
  content((73.86614173228347pt, 70.86614173228347pt), box([
			#set text(size: 6pt, fill: rgb(0%, 0%, 0%, 100%))
			x
		]))

})
